// SPAWN NAME FOR OVERALL REFERENCE IN MODULES
module.exports.SP_NAME = 'SP1';

// CREEP TYPE SPAWN LIMITS
module.exports.HARVESTER_LIMIT = 0;
module.exports.BUILDER_LIMIT = 0;
module.exports.UPGRADER_LIMIT = 5;
module.exports.REPAIRER_LIMIT = 0;
module.exports.CONT_REPAIRER_LIMIT = 0;
module.exports.WALL_REPAIRER_LIMIT = 1;
module.exports.TRANSPORTER_LIMIT = 7;


// CREEP TYPE SPAWN RATIO
module.exports.BUILDER_RATIO = 0.2;
module.exports.UPGRADER_RATIO = 0.4;
module.exports.WALL_REPAIRER_RATIO = 0.1;
module.exports.TRANSPORTER_RATIO = 0.5;


// CREEP TYPE ROLE LABELS
module.exports.ROLE_TRANSPORTER = 'transporter';
module.exports.ROLE_DEDICATED_HARVESTER = 'dedicatedHarvester';
module.exports.ROLE_HARVESTER = 'harvester';
module.exports.ROLE_BUILDER = 'builder';
module.exports.ROLE_UPGRADER = 'upgrader';
module.exports.ROLE_WALL_REPAIRER = 'wall_repairer';
module.exports.ROLE_CLAIMER = 'claimer';
module.exports.ROLE_SPAWN_BUILDER = 'spawn_builder';


// MINIMUM ENERGY IN ROOM TO ALLOW A NEW SPANW (SUSTAINABILTY, YO!)
module.exports.MINIMUM_ENERGY = 299;

// MINIMUM ENERGY IN ROOM TO ALLOW A NEW SPAWN (SUSTAINABILTY, YO!) 
// NEW VARIABLE FOR SPAWN RECOMMENDATION ROUTINE, BASED ON RATIO OF ENERGY CAPACITY
module.exports.MINIMUM_ENERGY_RATIO = 0.5;

// TICKS LEFT IN A HARVERSTER'S LIFE BEFORE SPAWNING IS SUSPENDED
module.exports.HARVERSTER_TICKS_LEFT = 100;

// TICKS LEFT IN CREEP'S LIFE BEFORE IT'S CONSIDERED USELESS (RETURN FOR FINAL TASK AND WAIT TO DIE!)
module.exports.TICKS_LEFT = 50;

// HITPOINTS LEFT IN A STRUCTURE BEFORE REPAIR CREEPS ARE CALLED IN FOR THE RESCUE (IN PERCENTAGE OF MAX HIT POINTS)
module.exports.REPAIR_THRESHOLD = 0.6;

// HITPOINTS LEFT IN A STRUCTURE TO WARRANT AN EMERGENGY REPAIR (HIGH PRIORITY)
module.exports.EMERGENCY_REPAIR_THRESHOLD = 0.3;

// ENERGY LEFT IN CONTAINER BEFORE SWITCHING TO A FULLER ONE
module.exports.CONTAINER_THRESHOLD = 0.5;

// ENERGY SITTING AROUND IN CONTAINERS THAT WARRANTS A NEW TRANSPORTER CREEP TO BE SPAWNED
module.exports.CONTAINER_IDLE_THRESHOLD = 0.4;

// ENERGY LEFT IN TOWER BEFORE REPAIR MODE IS DISABLED
module.exports.TOWER_REPAIR_THRESHOLD = 0.7;

// UPGRADER INDIVIDUAL ENERGY IN STORAGE FOR SPAWNING
module.exports.UPGRADER_STORAGE_ENERGY = 1000;

// ENERGY LEFT IN TOWER BEFORE CALLING FOR RECHARGE
module.exports.TOWER_RECHARGE_THRESHOLD = 0.85;

// INITIAL RAMPART MAINTENANCE PERFORMED BY TOWERS (UP UNTIL THIS AMOUNT OF HITPOINTS)
module.exports.RAMPART_INITIAL_REPAIR = 1000;